name: RecSysFramework
channels:
  - defaults
dependencies:
  - python=3.8
  - anaconda
  - Cython=0.29.23
  - h5py=3.1.0
  - nltk=3.6.1
  - nose=1.3.7
  - numpy=1.22.3
  - pandas=1.2.4
  - scikit-learn=0.24.1
  - scipy=1.8
  - networkx=3.1
  - tqdm=4.59.0
  - pytables=3.7.0
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::torchaudio=0.13.1
  - pytorch::pytorch-cuda=11.6
  - nvidia::cudatoolkit=11.6
  - conda-forge::lightfm==1.16
  - conda-forge::scikit-optimize=0.8.1
  - conda-forge::matplotlib=3.7.2
  
